### ISSUE TITLE
OS Version mismatch

### ISSUE THREAD

**Issue by equinusocio** [oieduardorabelo/use-user-agent#4]
![Screenshot 2021-10-29 at 15 09 14](https://user-images.githubusercontent.com/10454741/139440414-2df1ca48-3a19-456e-8a19-46f76ad85de7.png)

**Comment by oieduardorabelo** [comment]
we rely on https://github.com/faisalman/ua-parser-js to do the detection

please open the issue in their repo, thank you! 👍

**Comment by equinusocio** [comment]
Ref. https://github.com/faisalman/ua-parser-js/issues/564
